name: Daily YNAB Sync

on:
  schedule:
    # Run daily at 8 AM UTC (adjust timezone as needed)
    # You can change this to your preferred time
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual triggers from GitHub UI

jobs:
  sync-expenses:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Run YNAB sync
      env:
        CREDIT_CARD_USERNAME: ${{ secrets.CREDIT_CARD_USERNAME }}
        CREDIT_CARD_PASSWORD: ${{ secrets.CREDIT_CARD_PASSWORD }}
        YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
        BUDGET_ID: ${{ secrets.BUDGET_ID }}
        BARAK_CARD: ${{ secrets.BARAK_CARD }}
        ADI_CARD: ${{ secrets.ADI_CARD }}
      run: |
        echo "🚀 Starting daily YNAB sync..."
        npm start
        
    - name: Notify on success
      if: success()
      run: |
        echo "✅ YNAB sync completed successfully!"
        echo "Timestamp: $(date)"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ YNAB sync failed!"
        echo "Timestamp: $(date)"
        # You can add webhook notifications here if needed
        # For example, send to Slack, Discord, or email
